[tool.poetry]
name = "gblp"
version = "0.1.0"
description = "A project for working with Bloomberg and gRPC"
authors = ["Thomas Browne <your_email@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "gBLP" }]
python = "^3.9"

[tool.poetry.dependencies]
python = "^3.9"
grpcio = "^1.68.0"
grpcio-tools = "^1.68.0"
ipython = "^8.29.0"
certifi = "^2024.8.30"
cryptography = "^43.0.3"
rich = "^13.9.4"
numpy = "^2.1.3"
pandas = "^2.2.3"
polars = "^1.14.0"
psutil = "^6.1.0"
pytest = "^8.3.3"

# Dependencies that need a special index
blpapi = { version = "^3.24.10", source = "bloomberg" }

[tool.poetry.source]
name = "bloomberg"
url = "https://blpapi.bloomberg.com/repository/releases/python/simple/"
default = false

[tool.poetry.dev-dependencies]
# Add any development dependencies here if needed, like linters or test frameworks.

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

