# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloomberg.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62loomberg.proto\x12\tbloomberg\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n\x04Ping\x12\x0f\n\x07message\x18\x01 \x01(\t\"F\n\x04Pong\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1a\n\x0cKeyRequestId\x12\n\n\x02id\x18\x01 \x01(\t\"\\\n\x0bKeyResponse\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x0c\n\x04\x63\x65rt\x18\x02 \x01(\x0c\x12\x0e\n\x06\x63\x61\x63\x65rt\x18\x03 \x01(\x0c\x12\x12\n\nauthorised\x18\x04 \x01(\x08\x12\x0e\n\x06reason\x18\x05 \x01(\t2M\n\nKeyManager\x12?\n\nrequestKey\x12\x17.bloomberg.KeyRequestId\x1a\x16.bloomberg.KeyResponse\"\x00\x32\x31\n\x03\x42\x62g\x12*\n\x04ping\x12\x0f.bloomberg.Ping\x1a\x0f.bloomberg.Pong\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bloomberg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PING']._serialized_start=63
  _globals['_PING']._serialized_end=86
  _globals['_PONG']._serialized_start=88
  _globals['_PONG']._serialized_end=158
  _globals['_KEYREQUESTID']._serialized_start=160
  _globals['_KEYREQUESTID']._serialized_end=186
  _globals['_KEYRESPONSE']._serialized_start=188
  _globals['_KEYRESPONSE']._serialized_end=280
  _globals['_KEYMANAGER']._serialized_start=282
  _globals['_KEYMANAGER']._serialized_end=359
  _globals['_BBG']._serialized_start=361
  _globals['_BBG']._serialized_end=410
# @@protoc_insertion_point(module_scope)
