# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bloomberg_pb2 as bloomberg__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bloomberg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class KeyManagerStub(object):
    """Key management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.requestKey = channel.unary_unary(
                '/bloomberg.KeyManager/requestKey',
                request_serializer=bloomberg__pb2.KeyRequestId.SerializeToString,
                response_deserializer=bloomberg__pb2.KeyResponse.FromString,
                _registered_method=True)


class KeyManagerServicer(object):
    """Key management
    """

    def requestKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'requestKey': grpc.unary_unary_rpc_method_handler(
                    servicer.requestKey,
                    request_deserializer=bloomberg__pb2.KeyRequestId.FromString,
                    response_serializer=bloomberg__pb2.KeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bloomberg.KeyManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bloomberg.KeyManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyManager(object):
    """Key management
    """

    @staticmethod
    def requestKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.KeyManager/requestKey',
            bloomberg__pb2.KeyRequestId.SerializeToString,
            bloomberg__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BbgStub(object):
    """Bloomberg API session management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/bloomberg.Bbg/ping',
                request_serializer=bloomberg__pb2.Ping.SerializeToString,
                response_deserializer=bloomberg__pb2.Pong.FromString,
                _registered_method=True)
        self.pong = channel.unary_unary(
                '/bloomberg.Bbg/pong',
                request_serializer=bloomberg__pb2.Pong.SerializeToString,
                response_deserializer=bloomberg__pb2.Ping.FromString,
                _registered_method=True)
        self.subscriptionStream = channel.unary_stream(
                '/bloomberg.Bbg/subscriptionStream',
                request_serializer=bloomberg__pb2.ClientID.SerializeToString,
                response_deserializer=bloomberg__pb2.SubscriptionDataResponse.FromString,
                _registered_method=True)
        self.subscribe = channel.unary_unary(
                '/bloomberg.Bbg/subscribe',
                request_serializer=bloomberg__pb2.SubscriptionList.SerializeToString,
                response_deserializer=bloomberg__pb2.SubscriptionList.FromString,
                _registered_method=True)
        self.unsubscribe = channel.unary_unary(
                '/bloomberg.Bbg/unsubscribe',
                request_serializer=bloomberg__pb2.SubscriptionList.SerializeToString,
                response_deserializer=bloomberg__pb2.SubscriptionList.FromString,
                _registered_method=True)
        self.subscriptionInfo = channel.unary_unary(
                '/bloomberg.Bbg/subscriptionInfo',
                request_serializer=bloomberg__pb2.ClientID.SerializeToString,
                response_deserializer=bloomberg__pb2.SubscriptionList.FromString,
                _registered_method=True)
        self.historicalDataRequest = channel.unary_unary(
                '/bloomberg.Bbg/historicalDataRequest',
                request_serializer=bloomberg__pb2.HistoricalDataRequest.SerializeToString,
                response_deserializer=bloomberg__pb2.HistoricalDataResponse.FromString,
                _registered_method=True)
        self.intradayBarRequest = channel.unary_unary(
                '/bloomberg.Bbg/intradayBarRequest',
                request_serializer=bloomberg__pb2.IntradayBarRequest.SerializeToString,
                response_deserializer=bloomberg__pb2.IntradayBarResponse.FromString,
                _registered_method=True)


class BbgServicer(object):
    """Bloomberg API session management
    """

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subscriptionStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subscriptionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def historicalDataRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def intradayBarRequest(self, request, context):
        """rpc intradayTickRequest. maybe "tick" or "gblpTick"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BbgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=bloomberg__pb2.Ping.FromString,
                    response_serializer=bloomberg__pb2.Pong.SerializeToString,
            ),
            'pong': grpc.unary_unary_rpc_method_handler(
                    servicer.pong,
                    request_deserializer=bloomberg__pb2.Pong.FromString,
                    response_serializer=bloomberg__pb2.Ping.SerializeToString,
            ),
            'subscriptionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.subscriptionStream,
                    request_deserializer=bloomberg__pb2.ClientID.FromString,
                    response_serializer=bloomberg__pb2.SubscriptionDataResponse.SerializeToString,
            ),
            'subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=bloomberg__pb2.SubscriptionList.FromString,
                    response_serializer=bloomberg__pb2.SubscriptionList.SerializeToString,
            ),
            'unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.unsubscribe,
                    request_deserializer=bloomberg__pb2.SubscriptionList.FromString,
                    response_serializer=bloomberg__pb2.SubscriptionList.SerializeToString,
            ),
            'subscriptionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.subscriptionInfo,
                    request_deserializer=bloomberg__pb2.ClientID.FromString,
                    response_serializer=bloomberg__pb2.SubscriptionList.SerializeToString,
            ),
            'historicalDataRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.historicalDataRequest,
                    request_deserializer=bloomberg__pb2.HistoricalDataRequest.FromString,
                    response_serializer=bloomberg__pb2.HistoricalDataResponse.SerializeToString,
            ),
            'intradayBarRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.intradayBarRequest,
                    request_deserializer=bloomberg__pb2.IntradayBarRequest.FromString,
                    response_serializer=bloomberg__pb2.IntradayBarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bloomberg.Bbg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bloomberg.Bbg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bbg(object):
    """Bloomberg API session management
    """

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.Bbg/ping',
            bloomberg__pb2.Ping.SerializeToString,
            bloomberg__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.Bbg/pong',
            bloomberg__pb2.Pong.SerializeToString,
            bloomberg__pb2.Ping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def subscriptionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bloomberg.Bbg/subscriptionStream',
            bloomberg__pb2.ClientID.SerializeToString,
            bloomberg__pb2.SubscriptionDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.Bbg/subscribe',
            bloomberg__pb2.SubscriptionList.SerializeToString,
            bloomberg__pb2.SubscriptionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.Bbg/unsubscribe',
            bloomberg__pb2.SubscriptionList.SerializeToString,
            bloomberg__pb2.SubscriptionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def subscriptionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.Bbg/subscriptionInfo',
            bloomberg__pb2.ClientID.SerializeToString,
            bloomberg__pb2.SubscriptionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def historicalDataRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.Bbg/historicalDataRequest',
            bloomberg__pb2.HistoricalDataRequest.SerializeToString,
            bloomberg__pb2.HistoricalDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def intradayBarRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bloomberg.Bbg/intradayBarRequest',
            bloomberg__pb2.IntradayBarRequest.SerializeToString,
            bloomberg__pb2.IntradayBarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
